version: '2'
services:
    database:
        build: ./database
        ports:
            - "5432:5432"
    
    gateway:
        build: ./gateway
        ports:
            - "9999:9999"
        depends_on:
            - database
            - consul
            - zipkin
            - influxdb

    httpservice:
        build: ./httpservice
        ports:
            - "7777:7777"
        depends_on:
            - rabbitmq
            - consul
            - zipkin
            - influxdb

    rpcservice:
        build: ./rpcservice
        ports:
            - "6666:6666"
        depends_on:
            - rabbitmq
            - consul
            - zipkin
            - influxdb

    consul:
        image: consul
        ports:
            - "8500:8500"

    influxdb: 
        image: influxdb
        ports:
            - "8086:8086"

    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"

    rabbitmq:
        image: rabbitmq:3.6.6-management
        ports:
            - "15672:15672"
            - "5672:5672"
